name: Github Actions Maven Build Example

on:
 push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: STEP-1  - Checkout main branch from Github
      uses: actions/checkout@v2
    
    - name: STEP-2  - Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8   
        
    - name: STEP-3  - Set up a cache for Maven
      uses: actions/cache@v2
      with:
       path: ~/.m2
       key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
       restore-keys: ${{ runner.os }}-m2       
       
    - name: STEP-4 - Build with Maven
      run: mvn clean install

    - name: STEP-5 - JUNIT Test with Maven
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      
    - name: Test Report
      uses: kumvijaya/junit-test-reporter@main
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Junit Tests            # Name of the check run which will be created
        path: '**/target/surefire-reports/TEST-*.xml'   # Path to test results